// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneBox.Models;

namespace OneBox.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220125191923_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("OneBox.Models.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("OneBox.Models.Pack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CourierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecipientParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipientPhone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SenderParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderPhone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("RecipientParcelId");

                    b.HasIndex("SenderParcelId");

                    b.ToTable("Packs");
                });

            modelBuilder.Entity("OneBox.Models.ParcelLocker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParcelLockers");
                });

            modelBuilder.Entity("OneBox.Models.PostBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParcelLockerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParcelLockerId");

                    b.ToTable("PostBoxes");
                });

            modelBuilder.Entity("OneBox.Models.Pack", b =>
                {
                    b.HasOne("OneBox.Models.Courier", "Courier")
                        .WithMany()
                        .HasForeignKey("CourierId");

                    b.HasOne("OneBox.Models.ParcelLocker", "RecipientParcel")
                        .WithMany()
                        .HasForeignKey("RecipientParcelId");

                    b.HasOne("OneBox.Models.ParcelLocker", "SenderParcel")
                        .WithMany()
                        .HasForeignKey("SenderParcelId");

                    b.Navigation("Courier");

                    b.Navigation("RecipientParcel");

                    b.Navigation("SenderParcel");
                });

            modelBuilder.Entity("OneBox.Models.PostBox", b =>
                {
                    b.HasOne("OneBox.Models.ParcelLocker", "ParcelLocker")
                        .WithMany()
                        .HasForeignKey("ParcelLockerId");

                    b.Navigation("ParcelLocker");
                });
#pragma warning restore 612, 618
        }
    }
}
